import { SearchProviderContext } from "./context/search";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Carland",
  description: "Generated by Ankit Kansal",
};

export default function RootLayout({ children }) {
  return (
    <SearchProviderContext>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </SearchProviderContext>
  );
}
